image: Visual Studio 2017

install:
  - ps: gitversion /l console /output buildserver

configuration:
  - Release

dotnet_csproj:
  patch: true
  version: '$(GitVersion_SemVer)'

build_script:
- cmd: >-
    dotnet build

    dotnet pack

    7z a reportportal-%GitVersion_SemVer%-net452.zip ./src/ReportPortal.XUnitReporter/bin/%configuration%/net452/ReportPortal*

    7z a reportportal-%GitVersion_SemVer%-netcoreapp2.0.zip ./src/ReportPortal.XUnitReporter/bin/%configuration%/netcoreapp2.0/ReportPortal*

test: off

artifacts:
  - path: '**\*.zip'
  - path: '**\*.nupkg'